import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Navbar } from "@/components/Navbar";
import NavbarResponsive from "@/components/NavbarResponsive";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amarres de amor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {/* <Navbar /> */}
          <NavbarResponsive />
          {children}
        </main>
      </body>
    </html>
  );
}
